apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoshop-ingress
  namespace: banksystem
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:<ACCOUNT_ID>:certificate/<CERT_ID>
spec:
  rules:
    - host: demoshop.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demoshop-service
                port:
                  number: 80
